[package]
name = "matrix-multiply"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.16"
pollster = "0"
rand = "0"
bytemuck = "1"
futures-intrusive = "0.5"

#env_logger = "0.10"
